# Generated by Django 5.1.6 on 2025-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
